### ISSUE TITLE
No gem yet?

### ISSUE THREAD

**Issue by himdel** [RedHatCloudForms/cfme-versions#3]
```
$ gem install cfme-versions
ERROR:  Could not find a valid gem 'cfme-versions' (>= 0) in any repository
ERROR:  Possible alternatives: code_version, conversions, gem-versions, mime_version, api-versions
```

**Comment by NickLaMuro** [comment]
@himdel Nope, I don't think @Fryguy has pushed something yet.

**Comment by NickLaMuro** [comment]
@himdel That said, you should be able to add this repo to your `bundler.d/Gemfile.dev.rb` via the following line:


```ruby
gem 'cfme-versions', :git => "https://github.com/RedHatCloudForms/cfme-versions.git"
```

And that should install it for you when you do a `bin/bundle update`.

**Comment by himdel** [comment]
Indeed that works :)

But I'd rather use `alias miqversions=cfme-versions` than `alias miqversions='cd ~/manageiq ; bundle exec cfme-versions || bundle update && bundle exec cfme-versions` :)

**Comment by NickLaMuro** [comment]
@himdel I see, then yes, also a bit of a pain :)

If you really want, you can also do:

```
$ curl https://raw.githubusercontent.com/RedHatCloudForms/cfme-versions/master/lib/cfme-versions.rb > /usr/local/bin/cfme-versions
```

For the time being as well (or to your destination of choice).

**Comment by NickLaMuro** [comment]
@himdel or, now there is a gem!

https://rubygems.org/gems/cfme-versions

Enjoy!
